title: TM Test Stuff
description: Just for testing
theme: just-the-docs
#theme: jekyll-theme-slate
#logo: "your_logo_path"
#favicon_ico: "favicon.ico"

url: https://github.com/torte71/tmteststuff

aux_links:
  Repository: https://github.com/torte71/tmteststuff
