title: TM Test Stuff
description: Just for testing
theme: just-the-docs
#logo: "your_logo_path"
favicon_ico: "favicon.ico"
# search does not work with jekyll-relative-links :(
#search_enabled: false
# requires footer generation
#back_to_top: true
#back_to_top_text: "Back to top"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

#plugins:
#  - jekyll-relative-links

compress_html:
  ignore:
    envs: all

#url: https://torte71.github.io/tmteststuff
url: https://torte71.github.io
baseurl: "/tmteststuff"
repository: torte71/tmteststuff

aux_links:
  GitHub: https://github.com/torte71/tmteststuff
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
