title: TM Test Stuff
description: Just for testing
theme: just-the-docs
#theme: jekyll-theme-slate
#logo: "your_logo_path"
favicon_ico: "favicon.ico"
# search does not work with jekyll-relative-links :(
search_enabled: false
back_to_top: true
back_to_top_text: "Back to top"

plugins:
  - jekyll-relative-links

#url: https://github.com/torte71/tmteststuff
url: https://torte71.github.io/tmteststuff

aux_links:
  Repository: https://github.com/torte71/tmteststuff
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
